// TODO LANDING PAGE

//SHOW PRELOADER

// GET CURRENT DATABASE ENTRIES
//      STORE THEM IN AN ARRAY OF OBJECTS WITH NAME AND EMAIL

// CHECK IF USER HAS USED PAGE BEFORE
//      CHECK localSTORAGE
//      CHECK EMAIL AGAINST THE ARRAY TO SEE IF IT'S REGISTERED

// IF USER IS REGISTERED
//      SEND USER TO ASSET PAGE
//          (MAYBE SHOW MODAL FIRST SAYING WELCOME BACK??)

// IF USER ISN'T REGISTERED
//      HIDE PRELOADER AND SHOW PAGE

// HANDLE FORM DATA
//      CHECK FORM ENTRIES VALIDITY
//      SPLIT NAME INTO FIRST AND LAST NAME
//      CHECK EMAIL INPUTS ENDING TO GUESS IF IT'S WORK EMAIL OR NOT
//          IF EMAIL LOOKS TO BE PRIVATE DISPLAY "WARNING" MESSAGE
//      CHECK EMAIL INPUT ON WHETHER IT'S PRESENT IN DATABASE
//      CREATE AN OBJECT MATCHING OUR DATABASE TO STORE THE FORM DATA
//      SEND THAT DATA TO DATABASE
//      SHOW LOADER
//      AFTER DATA IS SUBMITTED SEND USER TO ASSET PAGE
